development: &default
  adapter: postgresql
  database: price_tracker_development
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  min_messages: warning

test:
  <<: *default
  database: price_tracker_test

production:
  <<: *default
  database: price_tracker_production
