development: &default
  adapter: postgresql
  database: furnitrackr_development
  encoding: utf8
  pool: 5
  min_messages: warning
  host: db
  username: postgres
  password: <%= ENV['PG_PASSWORD'] %>

test:
  <<: *default
  database: furnitrackr_test

production:
  <<: *default
  database: furnitrackr_production
